version: "3.5"

services:
  client:
    container_name: snarkos-client
    image: namaimichael/snarkos:latest
    volumes:
      - snarkos-client-vol:/aleo/data
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      RUST_LOG: "debug"
      SNARKOS_PORT: "0.0.0.0:4133"
      RPC_PORT: "0.0.0.0:3033"
      LOGLEVEL: "2"
      ALEO_PRIVKEY: 
    restart: unless-stopped
    command: ["/aleo/entrypoint.sh"]
    ports:
      - 3033:3033
      - 4133:4133

volumes:
  snarkos-client-vol:
