version: 2
jobs:
  build:
    docker:
      - image: 'docker:stable'
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: >-
          curl --silent -L --output ~/.docker/cli-plugins/docker-buildx
          https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker buildx version
      - run: |
          docker buildx build \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            --tag namaimichael/snarkos:testnet3-latest .
      - run:
          name: Tag Cros-build
          command: |
            BUILDX_PLATFORMS="$BUILDX_PLATFORMS" make cross-build
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    docker:
      - image: 'docker:stable'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: >
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER"
            --password-stdin

            docker push $IMAGE_NAME:latest
      - run: |
          docker buildx build --push \
            --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 
            --tag your-username/multiarch-example:buildx-latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: testnet3
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: testnet3
